on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      id: currenttag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.currenttag.outputs.tag }}
        name: Release ${{ steps.currenttag.outputs.tag }}
        body: |
          # Terraform Module - Azurerm Key Vault

          [![Terraform](https://github.com/visma-raet/terraform-azurerm-keyvault/actions/workflows/terraform.yml/badge.svg)](https://github.com/visma-raet/terraform-azurerm-keyvault/actions/workflows/terraform.yml)

          A [Terraform][2] module to deploys a Key Vault on Azure

          By [visma-raet][3]

          Use with:
          ```bash
          export ARM_CLIENT_ID=""
          export ARM_CLIENT_SECRET=""
          export ARM_SUBSCRIPTION_ID=""
          export ARM_TENANT_ID=""

          terraform init
          terraform apply
          ```

          ## License

          Licensed under [the MIT License][1].

          [1]: https://github.com/visma-raet/terraform-azurerm-keyvault/blob/devel/LICENSE
          [2]: https://www.terraform.io/
          [3]: https://www.vismaraet.nl/
